# Generated by Django 6.0.1 on 2026-01-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found')], max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('resolved', 'Resolved')], default='active', max_length=20)),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('documents', 'Documents'), ('accessories', 'Accessories'), ('bags', 'Bags'), ('clothing', 'Clothing'), ('keys', 'Keys'), ('other', 'Other'), ('jewelry', 'Jewelry')], max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=500)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('user_id', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('user_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('images', models.JSONField(default=list)),
                ('keywords', models.JSONField(blank=True, null=True)),
                ('reward', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'items',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='items_status_bc9bcb_idx'), models.Index(fields=['type'], name='items_type_d42d77_idx'), models.Index(fields=['category'], name='items_categor_694f25_idx'), models.Index(fields=['user_id'], name='items_user_id_bedce3_idx'), models.Index(fields=['created_at'], name='items_created_78d389_idx')],
            },
        ),
    ]
