# Generated by Django 6.0.1 on 2026-01-07 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(max_length=50, unique=True)),
                ('user_id', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('user_email', models.EmailField(max_length=254)),
                ('type', models.CharField(choices=[('inquiry', 'Inquiry'), ('complaint', 'Complaint'), ('suggestion', 'Suggestion'), ('technicalIssue', 'Technical Issue'), ('accountIssue', 'Account Issue'), ('other', 'Other')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('inProgress', 'In Progress'), ('waitingForUser', 'Waiting For User'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('subject', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('related_item_id', models.CharField(blank=True, max_length=255, null=True)),
                ('assigned_admin_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'support_tickets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id'], name='support_tic_user_id_f7e679_idx'), models.Index(fields=['status'], name='support_tic_status_ac1ffd_idx'), models.Index(fields=['priority'], name='support_tic_priorit_3536fa_idx'), models.Index(fields=['assigned_admin_id'], name='support_tic_assigne_9f5cac_idx'), models.Index(fields=['created_at'], name='support_tic_created_026818_idx')],
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('sender_id', models.CharField(max_length=255)),
                ('sender_name', models.CharField(max_length=255)),
                ('is_admin', models.BooleanField(default=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.supportticket')),
            ],
            options={
                'db_table': 'ticket_messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['ticket'], name='ticket_mess_ticket__5c3136_idx'), models.Index(fields=['sender_id'], name='ticket_mess_sender__e36217_idx'), models.Index(fields=['created_at'], name='ticket_mess_created_d4eba3_idx')],
            },
        ),
    ]
