# Generated by Django 6.0.1 on 2026-01-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('admin_id', models.CharField(max_length=255)),
                ('admin_name', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('userCreated', 'User Created'), ('userUpdated', 'User Updated'), ('userDeleted', 'User Deleted'), ('userSuspended', 'User Suspended'), ('userBanned', 'User Banned'), ('userActivated', 'User Activated'), ('userRoleChanged', 'User Role Changed'), ('passwordReset', 'Password Reset'), ('itemCreated', 'Item Created'), ('itemUpdated', 'Item Updated'), ('itemDeleted', 'Item Deleted'), ('itemArchived', 'Item Archived'), ('itemClosed', 'Item Closed'), ('itemImageDeleted', 'Item Image Deleted'), ('bulkItemsDeleted', 'Bulk Items Deleted'), ('bulkItemsArchived', 'Bulk Items Archived'), ('bulkItemsClosed', 'Bulk Items Closed'), ('matchCreated', 'Match Created'), ('matchApproved', 'Match Approved'), ('matchRejected', 'Match Rejected'), ('matchDismissed', 'Match Dismissed'), ('manualMatchCreated', 'Manual Match Created'), ('systemSettingChanged', 'System Setting Changed'), ('notificationSent', 'Notification Sent'), ('reportGenerated', 'Report Generated'), ('dataExported', 'Data Exported'), ('ticketResolved', 'Ticket Resolved'), ('ticketAssigned', 'Ticket Assigned'), ('adminLogin', 'Admin Login'), ('adminLogout', 'Admin Logout'), ('loginFailed', 'Login Failed')], max_length=50)),
                ('target_id', models.CharField(blank=True, max_length=255, null=True)),
                ('target_type', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin_id'], name='audit_logs_admin_i_a727ed_idx'), models.Index(fields=['action'], name='audit_logs_action_31f574_idx'), models.Index(fields=['target_id'], name='audit_logs_target__483e25_idx'), models.Index(fields=['created_at'], name='audit_logs_created_262184_idx')],
            },
        ),
    ]
