# Generated by Django 6.0.1 on 2026-01-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_items', models.IntegerField(default=0)),
                ('active_items', models.IntegerField(default=0)),
                ('resolved_items', models.IntegerField(default=0)),
                ('total_users', models.IntegerField(default=0)),
                ('pending_reports', models.IntegerField(default=0)),
                ('match_success_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('daily_trends', models.JSONField(default=list)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Dashboard Stats',
                'db_table': 'dashboard_stats',
            },
        ),
    ]
