# Generated by Django 6.0.1 on 2026-01-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmartMatch',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('lost_item_id', models.CharField(max_length=255)),
                ('found_item_id', models.CharField(max_length=255)),
                ('similarity_text', models.DecimalField(decimal_places=2, max_digits=5)),
                ('similarity_location', models.DecimalField(decimal_places=2, max_digits=5)),
                ('similarity_category', models.DecimalField(decimal_places=2, max_digits=5)),
                ('similarity_date', models.DecimalField(decimal_places=2, max_digits=5)),
                ('similarity_overall', models.DecimalField(decimal_places=2, max_digits=5)),
                ('match_type', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'matches',
                'ordering': ['-similarity_overall', '-created_at'],
                'indexes': [models.Index(fields=['lost_item_id'], name='matches_lost_it_afede7_idx'), models.Index(fields=['found_item_id'], name='matches_found_i_f419d4_idx'), models.Index(fields=['match_type'], name='matches_match_t_0c6248_idx'), models.Index(fields=['is_reviewed'], name='matches_is_revi_af9043_idx'), models.Index(fields=['is_dismissed'], name='matches_is_dism_58e58d_idx')],
            },
        ),
    ]
